from Tkinter import *
from tkMessageBox import *
import ttk
import Splash
import random
import time;
import datetime

root=Tk()
"""root.geometry("1920x720+0+0")"""
root.title("Train Ticket")
root.configure(background='black')

Top=Frame(root,width=1350,height=100,bd=14,relief='raise')

Top.pack(side=TOP)

f1=Frame(root,width=900,height=650,bd=8,relief='raise')
f1.pack(side=LEFT)
f2=Frame(root,width=440,height=650,bd=8,relief='raise')
f2.pack(side=RIGHT)

ft2=Frame(f2,width=440,height=650,bd=12,relief='raise')
ft2.pack(side=TOP)
fb2=Frame(f2,width=440,height=50,bd=16,relief='raise')
fb2.pack(side=BOTTOM)

f1a=Frame(f1,width=900,height=330,bd=8,relief='raise')
f1a.pack(side=TOP)
f2a=Frame(f1,width=900,height=320,bd=6,relief='raise')
f2a.pack(side=BOTTOM)

topLeft1=Frame(f1a,width=300,height=200,bd=16,relief='raise')
topLeft1.pack(side=LEFT)
topLeft2=Frame(f1a,width=300,height=200,bd=16,relief='raise')
topLeft2.pack(side=RIGHT)
topLeft3=Frame(f1a,width=300,height=200,bd=16,relief='raise')
topLeft3.pack(side=RIGHT)
#-------------------------------------------------------------------------------------------------  
bottomLeft1=Frame(f2a,width=450,height=450,bd=14,relief='raise')
bottomLeft1.pack(side=LEFT)
bottomLeft2=Frame(f2a,width=450,height=450,bd=14,relief='raise')
bottomLeft2.pack(side=RIGHT)

Date1=StringVar()
time1=StringVar() 
Ticketclass=StringVar()
TicketPrice=StringVar()
Child_Ticket=StringVar()
Adult_Ticket=StringVar()
From_Destination=StringVar()
To_Destination=StringVar()
Fee_Price=StringVar()
Route=StringVar()
Receipt_Ref=StringVar()
 
Ticketclass.set('')
TicketPrice.set('')
Child_Ticket.set('')
Adult_Ticket.set('')
From_Destination.set('')
To_Destination.set('')
Fee_Price.set('')
Route.set('')
Receipt_Ref.set('')
#--------------------------------------------------------------------------------------------
Top.configure(background='powder blue')
f1.configure(background='powder blue')
f2.configure(background='powder blue')
lblTitle=Label(Top,font='times 40 bold italic',text='Train Ticketing System',bd=10,width=42,height=1,justify='center')
lblTitle.grid(row=0,column=0)

lblReceipt=Label(ft2,font='times 20 bold italic',text='Travelling Ticketing System',bd=10,width=26,height=3
                 ,justify='center')
lblReceipt.grid(row=0,column=0)

lblClass1=Label(fb2,font='times 14 bold italic',text='Class',width=8,justify='center',relief='sunken')
lblClass1.grid(row=0,column=0)

lblClass2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Ticketclass)
lblClass2.grid(row=1,column=0)

lblTicket1=Label(fb2,font='times 14 bold italic',text='Ticket',width=8,justify='center',relief='sunken')
lblTicket1.grid(row=0,column=1)

lblTicket2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=TicketPrice)
lblTicket2.grid(row=1,column=1)

lblAdult1=Label(fb2,font='times 14 bold italic',text='Adult',width=8,justify='center',relief='sunken')
lblAdult1.grid(row=0,column=2)

lblAdult2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Adult_Ticket)
lblAdult2.grid(row=1,column=2)

lblChild1=Label(fb2,font='times 14 bold italic',text='Child',width=8,justify='center',relief='sunken')
lblChild1.grid(row=0,column=3)

lblChild2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Child_Ticket)
lblChild2.grid(row=1,column=3)

lblsp1=Label(fb2,font='times 18 bold',width=30,height=2,justify='center')
lblsp1.grid(row=2,column=0,columnspan=4)

lblFrom1=Label(fb2,font='times 14 bold italic',text='From',width=8,justify='center',relief='sunken')
lblFrom1.grid(row=3,column=1)

lblFrom2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=From_Destination)
lblFrom2.grid(row=3,column=2)

lblTo1=Label(fb2,font='times 14 bold italic',text='To',width=8,justify='center',relief='sunken')
lblTo1.grid(row=4,column=1)

lblTo2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=To_Destination)
lblTo2.grid(row=4,column=2)

lblPrice1=Label(fb2,font='times 14 bold italic',text='Price',width=8,justify='center',relief='sunken')
lblPrice1.grid(row=5,column=1)

lblPrice2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Fee_Price)
lblPrice2.grid(row=5,column=2)


lblsp3=Label(fb2,font='times 14 bold',width=34,height=2,justify='center')
lblsp3.grid(row=6,column=0,columnspan=4)

lblRefNo1=Label(fb2,font='times 14 bold italic',text='Ref No',width=8,justify='center',relief='sunken')
lblRefNo1.grid(row=7,column=0)

lblRefNo2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Receipt_Ref)
lblRefNo2.grid(row=8,column=0)

lblTime1=Label(fb2,font='times 14 bold italic',text='Time',width=8,justify='center',relief='sunken')
lblTime1.grid(row=7,column=1)

lblTime2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=time1)
lblTime2.grid(row=8,column=1)

lblDate1=Label(fb2,font='times 14 bold italic',text='Date',width=8,justify='center',relief='sunken')
lblDate1.grid(row=7,column=2)

lblDate2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Date1)
lblDate2.grid(row=8,column=2)

lblRoute1=Label(fb2,font='times 14 bold italic',text='Route',width=8,justify='center',relief='sunken')
lblRoute1.grid(row=7,column=3)

lblRoute2=Label(fb2,font='times 14 bold italic',width=8,justify='center',relief='sunken',textvariable=Route)
lblRoute2.grid(row=8,column=3)

#------------------------------------------------------------------------------------------------------
def iExit():
    qExit=askyesno("Quit System","Do you want to quit?")
    if qExit>0:
        root.destroy()
        return
def Reset():
    Tax.set('0')
    SubTotal.set('0')
    Total.set('0')
    var1.set('0')
    var2.set('0')
    var3.set('0')
    var4.set('0')
    var5.set('0')
    var6.set('0')
    var7.set('')
    var8.set('0')
    var9.set('')
    var10.set('0')
    var11.set('0')
    var12.set('0')
    Ticketclass.set("")
    TicketPrice.set("")
    Child_Ticket.set("")
    Adult_Ticket.set("")
    From_Destination.set("")
    To_Destination.set("")
    Fee_Price.set("")
    Receipt_Ref.set("")
    Route.set("")

def Travel_Cost():
    if (var9.get()=='Agra' and var1.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(223.84)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Agra' and var1.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(223.84)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Agra' and var1.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(196.36)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Agra' and var1.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(196.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)



    elif (var9.get()=='Bhopal' and var1.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(308.72)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Bhopal')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Bhopal' and var1.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(308.72)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Bhopal' and var1.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(238.72)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Bhopal')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Bhopal' and var1.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(196.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)

        
    elif (var9.get()=='Shimla' and var1.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(703.62)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Shimla' and var1.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(703.62)
        Return=float(var6.get())
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Shimla' and var1.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(608.98)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='v', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Shimla' and var1.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(608.98)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

        
    elif (var9.get()=='Kolkata' and var1.get()==1 and var4.get()==1 and var11.get==0):
        Tcost=float(1042.65)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var1.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1042.65)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)



    elif (var9.get()=='Kolkata' and var1.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(988.33)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var1.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(988.33)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Jaipur' and var1.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(878.33)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var1.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(878.33)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var1.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(786.32)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var1.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(786.32)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Standard')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

        

    elif (var9.get()=='Agra' and var2.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(458.36)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Agra' and var2.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(458.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Agra' and var2.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(397.36)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Agra' and var2.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(397.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Bhopal' and var2.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(625.50)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Bhopal')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Bhopal' and var2.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(625.50)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Bhopal' and var2.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(575.39)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Bhopsl')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Bhopal' and var2.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(575.39)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)



        
    elif (var9.get()=='Shimla' and var2.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(1098.24)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Shimla' and var2.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1098.24)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Shimla' and var2.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(995.42)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Shimla' and var2.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(995.42)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var2.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(1998.22)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Kolkata' and var2.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1998.22)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var2.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(1632.58)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Kolkata' and var2.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(1632.58)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var2.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(1478.98)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Jaipur' and var2.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1478.98)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var2.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(1360.11)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('EFL'+randomRef)

    elif (var9.get()=='Jaipur' and var2.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(1360.11)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('Economy')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Agra' and var3.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(889.36)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Agra' and var3.get()==1 and var4.get()==1 and var11.get()==1):
         
        Tcost=float(889.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Agra' and var3.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(745.36)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Agra')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Agra' and var3.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(745.36)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Agra')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Bhopal' and var3.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(1458.42)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Bhopal')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Bhopal' and var3.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1458.42)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Bhopal' and var3.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(1311.55)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Bhopsl')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Bhopal' and var3.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(1311.55)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Bhopal')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)
        
    elif (var9.get()=='Shimla' and var3.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(2515.57)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Shimla' and var3.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(2515.57)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)


    elif (var9.get()=='Shimla' and var3.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(2389.22)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Shimla')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Shimla' and var3.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(2389.22)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Shimla')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var3.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(3269.21)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Kolkata' and var3.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(3269.21)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Kolkata' and var3.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(3085.33)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Kolkata')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Kolkata' and var3.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(3085.33)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Kolkata')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var3.get()==1 and var4.get()==1 and var11.get()==0):
        Tcost=float(1635.32)
        Single=float(var12.get())
        Adult_Tax='₹', str('%2f'%((Tcost*Single)*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+((Tcost*Single)*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Jaipur' and var3.get()==1 and var4.get()==1 and var11.get()==1):
        Tcost=float(1635.32)
        Single=float(var12.get())
        Return=float(var6.get())
        Adult_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0.03))
        Adult_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0.03)))
        Tax.set(Adult_Tax)
        SubTotal.set(Adult_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Adult_Fees)
        Child_Ticket.set('No')
        Adult_Ticket.set('Yes')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)

    elif (var9.get()=='Jaipur' and var3.get()==1 and var5.get()==1 and var11.get()==0):
        Tcost=float(1499.27)
        Single=float(var12.get())
        Child_Tax='₹', str('%2f'%(Tcost*0))
        Child_Fees='₹', str('%2f'%(Tcost*Single))
        TotalCost='₹', str('%2f'%((Tcost*Single)+(Tcost*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Guna')
        To_Destination.set('Jaipur')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('FFL'+randomRef)

    elif (var9.get()=='Jaipur' and var3.get()==1 and var5.get()==1 and var11.get()==1):
        Tcost=float(1499.27)
        Single=float(var12.get())
        Return=float(var6.get())
        Child_Tax='₹', str('%2f'%((Tcost*(Single+Return))*0))
        Child_Fees='₹', str('%2f'%(Tcost*(Single+Return)))
        TotalCost='₹', str('%2f'%((Tcost*(Single+Return))+((Tcost*(Single+Return))*0)))
        Tax.set(Child_Tax)
        SubTotal.set(Child_Fees)
        Ticketclass.set('First Class')
        TicketPrice.set(Child_Fees)
        Child_Ticket.set('Yes')
        Adult_Ticket.set('No')
        From_Destination.set('Jaipur')
        To_Destination.set('Guna')
        Fee_Price.set(TotalCost)
        Total.set(TotalCost)
        Route.set('Direct')

        x=random.randint(109,5876)
        randomRef=str(x)
        Receipt_Ref.set('TFL'+randomRef)




def chkbutton_value():
    if(var10.get()==1):
        var12.set("")
        entSingle.configure(state=NORMAL)
    elif var10.get()==0:
        entSingle.configure(state=DISABLED)
        var12.set('0')
    if(var11.get()==1):
        var6.set("")
        entReturn.configure(state=NORMAL)
    elif var11.get()==0:
        entReturn.configure(state=DISABLED)
        var6.set('0')
    
        
        
#-----------------------------------------------------------------------------------------
var1=IntVar()
var2=IntVar()
var3=IntVar()
var4=IntVar()
var5=IntVar()
var6=StringVar()
var7=StringVar()
var8=StringVar()
var9=StringVar()
var10=IntVar()
var11=IntVar()
var12=IntVar()
Tax=StringVar()
SubTotal=StringVar()
Total=StringVar()
text_Input=StringVar()

var1.set('0')
var2.set('0')
var3.set('0')
var4.set('0')
var5.set('0')
var6.set('0')
var7.set('')
var8.set('0')
var9.set('0')
var10.set('0')
var11.set('0')
var12.set('0')

#-------------------------------------------------------------------------------------------
Date1.set(time.strftime("%d/%m/%Y"))
time1.set(time.strftime('%H:%M:%S'))
#-------------------------------------------------------------------------------------------

lblClass=Label(topLeft1,font='times 22 bold italic',text='Class',bd=8)
lblClass.grid(row=0,column=0,sticky=W)
chkstandard=Checkbutton(topLeft1,font='times 20 bold italic',text='Standard',variable=var1,onvalue=1,offvalue=0)
chkstandard.grid(row=1,column=0,sticky=W)
chkEconomy=Checkbutton(topLeft1,font='times 20 bold italic',text='Economy',variable=var2,onvalue=1,offvalue=0)
chkEconomy.grid(row=2,column=0,sticky=W)
chkFirstClass=Checkbutton(topLeft1,font='times 20 bold italic',text='First Class',variable=var3,onvalue=1,offvalue=0)
chkFirstClass.grid(row=3,column=0,sticky=W)
#-------------------------------------------------------------------------------------------


lblSelect=Label(topLeft3,font='times 22 bold italic',text='Destination Selector',bd=8)
lblSelect.grid(row=0,column=0,sticky=W,columnspan=2)
lblDestination=Label(topLeft3,font='times 20 bold italic',text='Destination',bd=4)
lblDestination.grid(row=1,column=0,sticky=W)

cb0Destination= ttk.Combobox(topLeft3,textvariable=var9,state='readonly',font='times 20 bold italic',width=8)
cb0Destination['value']=('','Agra','Bhopal','Shimla','Kolkata','Jaipur')
cb0Destination.current(0)
cb0Destination.grid(row=1,column=1)

chkAdult=Checkbutton(topLeft3,font='times 20 bold italic',text='Adult',variable=var4,onvalue=1,offvalue=0)
chkAdult.grid(row=2,column=0,sticky=W)
chkChild=Checkbutton(topLeft3,font='times 20 bold italic',text='Child',variable=var5,onvalue=1,offvalue=0)
chkChild.grid(row=3,column=0,sticky=W)
#-----------------------------------------------------------------------------------------------------------------------


lblClass=Label(topLeft2,font='times 22 bold italic',text='Ticket Type',bd=8)
lblClass.grid(row=0,column=0,sticky=W)
chkSingle=Checkbutton(topLeft2,font='times 20 bold italic',text='Single',variable=var10,onvalue=1,offvalue=0,command=chkbutton_value)
chkSingle.grid(row=1,column=0,sticky=W)
entSingle=Entry(topLeft2,font='times 20 bold italic',textvariable=var12,bd=2,width=8,state=DISABLED)
entSingle.grid(row=1,column=1,sticky=W)
chkReturn=Checkbutton(topLeft2,font='times 20 bold italic',text='Return',variable=var11,onvalue=1,offvalue=0,command=chkbutton_value)
chkReturn.grid(row=2,column=0,sticky=W)
entReturn=Entry(topLeft2,font='times 20 bold italic',textvariable=var6,bd=2,width=8,state=DISABLED)
entReturn.grid(row=2,column=1,sticky=W)
lblComment=Label(topLeft2,font='times 20 bold italic',text='Comment',bd=8)
lblComment.grid(row=3,column=0,sticky=W)
entComment=Entry(topLeft2,font='times 20 bold italic',textvariable=var7,bd=2,width=8)
entComment.grid(row=3,column=1,sticky=W)
#------------------------------------------------------------------------------------------------------------------

text_Input=StringVar()
txtDisplay=Entry(bottomLeft2,width=21,font='times 20 bold',textvariable=text_Input,bd=8,bg='powder blue',justify='right')
txtDisplay.grid(columnspan=5)

def insert(x):
    txtDisplay.insert(21,x)

def clear():
    txtDisplay.delete(0,END)

def result():
    y=eval(txtDisplay.get())
    clear()
    txtDisplay.insert(21,y)

btn7=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='7',bg='powder blue',command=lambda:insert(9)).grid(row=2,column=0)
btn8=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='8',bg='powder blue',command=lambda:insert(8)).grid(row=2,column=1)
btn9=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='9',bg='powder blue',command=lambda:insert(9)).grid(row=2,column=2)
Addition=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='+',bg='powder blue',command=lambda:insert('+')).grid(row=2,column=3)
btn4=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='4',bg='powder blue',command=lambda:insert(4)).grid(row=3,column=0)
btn5=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='5',bg='powder blue',command=lambda:insert(5)).grid(row=3,column=1)
btn6=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='6',bg='powder blue',command=lambda:insert(6)).grid(row=3,column=2)
Subtration=Button(bottomLeft2,height=3,width=8,bd=8,fg='black',font='times 10 bold',text='-',bg='powder blue',command=lambda:insert('-')).grid(row=3,column=3)
btn1=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='1',bg='powder blue',command=lambda:insert(1)).grid(row=4,column=0)
btn2=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='2',bg='powder blue',command=lambda:insert(2)).grid(row=4,column=1)
btn3=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='3',bg='powder blue',command=lambda:insert(3)).grid(row=4,column=2)
Multiply=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='*',bg='powder blue',command=lambda:insert('*')).grid(row=4,column=3)
btn0=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='0',bg='powder blue',command=lambda:insert(0)).grid(row=5,column=0)
btnClear=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='C',command=clear,bg='powder blue').grid(row=5,column=1)
btnEquals=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='=',command=result,bg='powder blue').grid(row=5,column=2)
Division=Button(bottomLeft2,width=8,height=3,bd=8,fg='black',font='times 10 bold',text='/',bg='powder blue',command=lambda:insert('/')).grid(row=5,column=3)
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

lblStateTax=Label(bottomLeft1,font='times 24 bold',text='State Tax',bd=16,anchor='w')
lblStateTax.grid(row=3,column=2)
txtStateTax=Entry(bottomLeft1,font='times 16 bold',textvariable=Tax,bd=10,width=22,bg='#ffffff',justify='right')
txtStateTax.grid(row=3,column=3)
lblSubTotal=Label(bottomLeft1,font='times 24 bold',text='Sub Total',bd=16,anchor='w')
lblSubTotal.grid(row=4,column=2)
txtSubTotal=Entry(bottomLeft1,font='times 16 bold',textvariable=SubTotal,bd=10,width=22,bg='#ffffff',justify='right')
txtSubTotal.grid(row=4,column=3)
lblTotalCost=Label(bottomLeft1,font='times 24 bold',text='Total Cost',bd=16,anchor='w')
lblTotalCost.grid(row=5,column=2)
txtTotalCost=Entry(bottomLeft1,font='times 16 bold',textvariable=Total,bd=10,width=22,bg='#ffffff',justify='right')
txtTotalCost.grid(row=5,column=3)
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
lblsp=Label(fb2,font='times 14 bold',width=34,height=1,justify='center')
lblsp.grid(row=11,column=0,columnspan=4)

lblsp2=Label(fb2,font='times 14 bold',width=34,height=2,justify='center')
lblsp2.grid(row=9,column=0,columnspan=4)
#--------------------------------------------------------------------------------------------------------------------------------

btnTotal=Button(fb2,text='Total',bd=2,bg='powder blue',fg='black',font='times 12 bold',width=6,height=2,command=Travel_Cost).grid(row=10,column=0)
btnReset=Button(fb2,text='Reset',bd=2,bg='powder blue',fg='black',font='times 12 bold',width=6,height=2,command=Reset).grid(row=10,column=1)
btnClear=Button(fb2,text='Clear',bd=2,bg='powder blue',fg='black',font='times 12 bold',width=6,height=2,command=Reset).grid(row=10,column=2)
btnExit=Button(fb2,text='Exit',bd=2,bg='powder blue',fg='black',font='times 12 bold',width=6,height=2,command=iExit).grid(row=10,column=3)
root.mainloop()
